[package]
name = "faster_unicode_symbol_search"
version = "0.1.0"
authors = ["Nickolas Fotopoulos <nickolas.fotopoulos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "0.2"
rayon = "1.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false
