[tasks.build]
command = "cargo"
args = ["build", "--release", "--target", "aarch64-apple-darwin"]

[tasks.package]
clear = true # clear original meaning of package command
description = "Package up an Alfred workflow ready for installation"
script = [
    '''
TEMP_DIR=$(mktemp -d)
cp target/aarch64-apple-darwin/release/fuss "${TEMP_DIR}"
cp doc/icon.png "${TEMP_DIR}"
cp info.plist "${TEMP_DIR}"
pushd "${TEMP_DIR}"
zip "${CARGO_MAKE_WORKING_DIRECTORY}/Faster Unicode Symbol Search.alfredworkflow" *
popd
rm -rf "${TEMP_DIR}"
''',
]
dependencies = ["build"]
